### ISSUE TITLE
jupinx-quickstart error

### ISSUE THREAD

**Issue by phantomachine** [QuantEcon/jupinx#103]
Hello, I've been attempting to use **jupinx**, but can't get past the ``jupinx-quickstart`` step.

I have ``sphinx 4.4.0`` installed.

Here's my error message:

$ jupinx-quickstart

Traceback (most recent call last):
  File "/home/myhome/anaconda3/bin/jupinx-quickstart", line 5, in <module>
    from jupinx.cmd.quickstart import main
  File "/home/myhome/anaconda3/lib/python3.9/site-packages/jupinx/cmd/quickstart.py", line 41, in <module>
    from sphinx.deprecation import RemovedInSphinx40Warning
ImportError: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' (/home/myhome/anaconda3/lib/python3.9/site-packages/sphinx/deprecation.py)

Thanks in advance for any suggestions.

**Comment by phantomachine** [comment]
Fixed it, sort of. 

I had to create another environment with 

- ``python=3.6``
- ``sphinx=4.0.2``

Any plans to update ``jupinx`` to play nice with the latest version of ``python`` and ``sphinx-doc``?
